### PR TITLE
config/v1/config.json added.

### PR DESCRIPTION
**Pull request by kerzmaximilian**
@herkulano @petcupaula: Discussed with @fnobilia to add the configuration file to the schema repository. I also added a `../vX/..` to the route. I am assuming that layouts will change and maybe we want to support multiple versions. Let me know if that is to convoluted and I'll remove it from the path.

@fnobilia could you have a look at format and documentation?

### CODE REVIEW

**Comment by fnobilia** [comment]
@kerzmaximilian I suggested to store this schema here to have all `RADAR-CNS schemas` in the same repository.

**Comment by kerzmaximilian** [comment]
@fnobilia yep - good point! It might be better to remove the versioning from the config file and apply it to the entire api down the line if there are major changes? (Eg.: `https://z.z.z.z:80/v1/...`)

**Comment by fnobilia** [comment]
@kerzmaximilian what do you mean?

**Comment by kerzmaximilian** [comment]
@fnobilia just quickly putting in writing what we discussed: generally agree to versioning of the api, but as you suggested, it is better to do this through versioned containers and nginx.

**Pull request closed without merging**
