### PR TITLE
prepare release

### PR DESCRIPTION
**Pull request by nivemaham**
Is there anything else we should do to prepare a new release of RADAR-Schemas? @blootsvoets

### CODE REVIEW

**Comment by yatharthranjan** [comment]
Hi @nivemaham, We need to add schemas and specifications for the aRMT app for all the questionnaires. @kerzmaximilian will need them for the release of aRMT before this wednesday

**Comment by nivemaham** [comment]
@yatharthranjan , I am waiting for the confirmation of @blootsvoets for the release. Do you need the released distribution? i do not expect changes in the specifications or schemas. We should be able to do the release tomorrow, i believe.

**Comment by yatharthranjan** [comment]
If we add the schemas and specification to the repo, will these be automatically registered without them in the release?

**Comment by blootsvoets** [comment]
@yatharthranjan we can make a new release when the aRMT schemas get added. They will not be automatically be used until they are released _and_ the `kafka-radarinit` image is updated with the new release version. In RADAR-Docker, you can add specifications and schemas which are not yet released by adding them to the `commons` and `specifications` directories in `etc/schema`.

**Pull request merged**
