### PR TITLE
Dashboard config

### PR DESCRIPTION
**Pull request by kerzmaximilian**
@herkulano could you have a quick review of the schema? If alright, Francesco will deploy it.

### CODE REVIEW

**Comment by fnobilia** [comment]
Max, I would suggest to put it on folder different from `REST API`. Maybe dashboard, labels.

**Comment by fnobilia** [comment]
@kerzmaximilian I'd suggest to move this configuration in `Firebase`, in this way all RADAR remote config files will be in a single place.

**Comment by herkulano** [comment]
@kerzmaximilian agree with @fnobilia moving it to Firebase.

**Comment by fnobilia** [comment]
Agreed on moving the configuration file on `Firebase`. I leave the branch opened, in this way the config file will be still accessible via `REST-Api`. I will remove the branch when the `Firebase` implementation will be finalised.

@herkulano @kerzmaximilian

**Pull request closed without merging**
